apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shop-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop-deployment
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
# Это неправильная метрика для моего примера, она означает, что каждую минуту можно увеличить, на 100% количество подов
#        - type: Percent
#          value: 100
#          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
# Это неправильная настройка, говорит можно уменьшить, до 10 подов за раз, в период 60 секунд.
#        - type: Pods
#          value: 10
#          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80