apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  labels:
    app: shop-metadata

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: shop-label
  template:
    metadata:
      labels:
        app: shop-label
    spec:
      containers:
        - name: shop
          image: shop:2.0
          envFrom:
            - configMapRef:
                name: shop-config
          ports:
            - containerPort: 8080 # просто "справочная" информация для того чтобы понимать на какой порт обращаться

---
apiVersion: v1
kind: Service
metadata:
  name: shop-service

spec:
  type: NodePort
  selector:
    app: shop-label
  ports:
    - port: 8080 # порт, который идет наружу. Может даже не совпадать с targetPort
      targetPort: 8080 # реальный порт имеджа, обязан совпадать с server.port