spring:
  application:
    name: shop

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

app:
  environment: ${APP_ENVIRONMENT:local}
  greeting-message: ${GREETING_MESSAGE:Hello from default config}
  password: ${PASSWORD:no password}

clients:
  bank-url: ${BANK_URL:http://localhost:8080}

server:
  port: ${SERVER_PORT:8081}