apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load-generator

spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-first-app
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      containers:
        - name: nginx
          image: busybox:1
          command: ["/bin/sh", "-c", "while true; do wget -q -O- http://shop-service:8080/shop/api; sleep 0.1; done"]