apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job

spec:
  schedule: "* * * * *"
#  successfulJobsHistoryLimit: 2
#  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: job
              image: busybox
              command: [ "echo", "Hello from Cron Job!" ]