apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job

spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: job
          image: busybox
          command: ["echo", "Processing task"]