apiVersion: v1
kind: Service
metadata:
  name: app-test-service

spec:
  type: NodePort
  selector:
    app: app-test-label
  ports:
    - port: 8080 #порт, который идет наружу. Может даже не совпадать с targetPort
      targetPort: 8080 # реальный порт имеджа, обязан совпадать с server.port